# Generated by Django 2.1.1 on 2018-10-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Security',
            new_name='Asset',
        ),
    ]
