# Generated by Django 2.1.1 on 2018-10-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_add_asset_date_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='date_bought',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='date_sold',
        ),
    ]
