# Generated by Django 2.1.1 on 2018-10-05 14:50

from django.db import migrations, models
from robinhood.models import Stock, Option
from portfolios.models import Asset

def set_instrument_urls(apps, schema_editor):
    for asset in Asset.objects.all():
        if not asset.instrument_url:
            instrument_url = None
            if asset.type == Asset.STOCK:
                instrument_url = Stock.resource_url(asset.instrument_id)
            elif asset.type == Asset.OPTION:
                instrument_url = Option.resource_url(asset.instrument_id)
            asset.instrument_url = instrument_url
            asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_remove_asset_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_acquired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='date_released',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='instrument_url',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.RunPython(set_instrument_urls)
    ]
