# Generated by Django 2.1.1 on 2019-01-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_add_asset_date_and_instrument_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='instrument_id',
            field=models.UUIDField(null=True),
        ),
    ]
