# Generated by Django 2.2.2 on 2019-07-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_add_asset_instrument_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
    ]
