# Generated by Django 2.2.2 on 2019-07-17 22:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexes.User')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.UUIDField(null=True)),
                ('instrument_url', models.CharField(max_length=160, null=True)),
                ('identifier', models.CharField(max_length=32)),
                ('count', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('S', 'stock'), ('O', 'option')], max_length=6)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexes.Index')),
            ],
        ),
    ]
