# Generated by Django 5.1.3 on 2025-05-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='index',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
