# Generated by Django 4.0.2 on 2022-02-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='index',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
