# Generated by Django 2.1.1 on 2018-10-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_security_to_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='symbol',
            new_name='name',
        ),
    ]
