# Generated by Django 2.1.1 on 2018-10-01 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rename_portfolio_symbol_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_bought',
            field=models.DateTimeField(null=True,default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='date_sold',
            field=models.DateTimeField(null=True),
        ),
    ]
